libs: 
	  (cd LIBFEMTOGL;   make clean all) # Compile graphic library
	  (cd LIBFEMTORV32; make clean all) # Compile hardware support lib
	  (cd LIBFEMTOC;    make clean all) # Compile lib with printf() replacement function
	  (cd CRT;          make clean all) # Compile C runtime for baremetal
	  (cd MULTICMP_LIB; make clean all) # my custom multicmp library
	  @echo ==== Generated femtorv32 libs.
